### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by sk1350** [huangyh09/diceseq#5]
Hello I am trying to look at changes in isoform expression between different Xenopus development stages. I have used HISAT for alignment and the .gtf file is from Ensembl: 

my_sam_list=SRR489459.sorted.bam---SRR489460.sorted.bam---SRR489462.sorted.bam
diceseq -a Xenopus_tropicalis.Xenopus_tropicalis_v9.1.98.gtf -s $my_sam_list -t 6,8,10 -o dice_seq_output.txt

And it gave me this error:
……………
Cannot fetch reads in region: KV466212.1:259-1340
Cannot fetch reads in region: KV467030.1:200-961
Cannot fetch reads in region: KV467044.1:156-274
Cannot fetch reads in region: KV467044.1:420-528
Cannot fetch reads in region: KV467044.1:671-789
Cannot fetch reads in region: KV467044.1:935-1053
Cannot fetch reads in region: MT:1082-2716
Traceback (most recent call last):
  File "/users/sk1350/.conda/envs/diceseq_env/bin/diceseq", line 8, in <module>
    sys.exit(main())
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/diceseq.py", line 239, in main
    sort_dice_file(out_file+".dice", tran_ids)
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/utils/run_utils.py", line 41, in sort_dice_file
    idx = id_mapping(tran_ids, data[1:, 0])
IndexError: too many indices for array

**Comment by huangyh09** [comment]
Hi,

It seems that there are no splicing events have been reported in the initial .dice file, hence the sorting failed. Do you only have five splicing events and all of them can't be fetched? BTW, could you also check if the chromosome id matches between GTF and bam files, e.g., KV466212.1.

Yuanhua

**Comment by sk1350** [comment]
Hello, 
Thank you for your advice. I switched to a different annotation file to make sure it matches the bam files. However, I am now getting a new error. I checked and it seems to have the right "ensembl like" format. 

diceseq -a XENTR_9.1_Xenbase.gff3 $my_sam_list -t 6,8,10,13,16,24 -o out_file
[DICEseq] loading annotation file...Traceback (most recent call last):
  File "/users/sk1350/.conda/envs/diceseq_env/bin/diceseq", line 8, in <module>
    sys.exit(main())
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/diceseq.py", line 121, in main
    genes = loadgene(options.anno_file)
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/utils/gtf_utils.py", line 234, in loadgene
    if aLine[0] != _gene.trans[-1].chrom:
IndexError: list index out of range

**Comment by huangyh09** [comment]
Hi,
Indeed, it looks the issue comes from the GTF format incompatibility. It requires format as: gene --> transcript 1 --> exon1 --> exon2 ... -> transcript 2 exon1 --> exon3 ....
Example is here: http://diceseq.sourceforge.net/manual.html#annotation-format

Best,
Yuanhua
